version: "3.8"

networks:
  bookstore:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
    name: bookstore

services:
  bookstore:
    build:
      context: .
      dockerfile: ./compose/bookstore/Dockerfile
    container_name: bookstore-api
    depends_on:
      - database
    env_file:
      - ./.envs/.bookstore
    networks:
      - bookstore
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    volumes:
      - ./src/:/usr/src/bookstore/
      - bookstore_media:/usr/share/bookstore/media/
      - bookstore_static:/usr/share/bookstore/static/
  database:
    image: postgres:13.0
    container_name: bookstore-database
    env_file:
      - ./.envs/.postgres
    networks:
      - bookstore
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  bookstore_media: {}
  bookstore_static: {}
  postgres_data: {}
