version: "3.8"

networks:
  bookstore:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
    name: bookstore

services:
  bookstore:
    build:
      context: .
      dockerfile: ./compose/bookstore/Dockerfile
    container_name: bookstore-api
    depends_on:
      - database
    env_file:
      - ./.envs/.bookstore
    expose:
      - 8000
    networks:
      - bookstore
    restart: always
    volumes:
      - ./manage.py:/usr/src/bookstore/manage.py
      - ./bookstore/:/usr/src/bookstore/bookstore/
      - bookstore_media:/usr/share/bookstore/media/
      - bookstore_static:/usr/share/bookstore/static/
  database:
    image: postgres:13.0
    container_name: bookstore-database
    env_file:
      - ./.envs/.postgres
    networks:
      - bookstore
    restart: always
    volumes:
      - bookstore_database_data:/var/lib/postgresql/data/

volumes:
  bookstore_media:
    name: bookstore-media
  bookstore_static:
    name: bookstore-static
  bookstore_database_data:
    name: bookstore-database
