# Generated by Django 3.0.3 on 2020-02-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('format', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=31)),
                ('ean', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('available', models.PositiveSmallIntegerField()),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_discounted', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=4095)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers')),
                ('cover_url', models.URLField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.Author')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.Binding')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='publisher.Publisher')),
            ],
        ),
    ]
