# Generated by Django 2.1.2 on 2018-10-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('format', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=31)),
                ('ean', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('available', models.PositiveSmallIntegerField()),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_discounted', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=4095)),
                ('cover', models.ImageField(upload_to='covers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookstore.Author')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookstore.Binding')),
            ],
        ),
    ]
