# Generated by Django 3.1.2 on 2020-10-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('publishers', '0001_initial'),
        ('bindings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('format', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=31)),
                ('ean', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('available', models.PositiveSmallIntegerField()),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_discounted', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=4095)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers')),
                ('cover_url', models.URLField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.author')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bindings.binding')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='publishers.publisher')),
            ],
        ),
    ]
