# Generated by Django 3.1.2 on 2020-11-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('PAID', 'Paid'), ('COMPLETE', 'Complete'), ('ABANDONED', 'Abandoned')], max_length=10),
        ),
    ]
