# Generated by Django 3.1.2 on 2020-11-07 22:13

import bookstore.carts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20201107_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('PAID', 'Paid'), ('COMPLETE', 'Complete'), ('ABANDONED', 'Abandoned')], default=bookstore.carts.models.CartStatus['NEW'], max_length=10),
        ),
    ]
